#include "IconFactory.h"
#include <juce_core/juce_core.h>
#include <juce_graphics/juce_graphics.h>
// BinaryData is generated by juce_add_binary_data
#include "BinaryData.h"

// BinaryData is generated by juce_add_binary_data
namespace
{
    std::unique_ptr<juce::Drawable> createDrawableFromData(const char* data, int size)
    {
        if (data == nullptr || size == 0)
            return nullptr;

        std::unique_ptr<juce::XmlElement> xml = juce::XmlDocument::parse(juce::String::fromUTF8(data, size));
        if (xml == nullptr)
            return nullptr;

        return juce::Drawable::createFromSVG(*xml);
    }
}

namespace Icons
{
    std::unique_ptr<juce::Drawable> load(const juce::String& name)
    {
        int size = 0;

        auto* data = BinaryData::getNamedResource(
            (name + "_svg").toRawUTF8(),
            size
        );

        return createDrawableFromData(data, size);
    }

    std::unique_ptr<juce::Drawable> load(const juce::String& name,
        juce::Colour tint)
    {
        auto drawable = load(name);

        if (drawable != nullptr)
            drawable->replaceColour(juce::Colours::black, tint);

        return drawable;
    }
}
